---
- hosts: all
  become: true
  tasks:
    - name: Update package cache,apache2,php
      tags: always
      package:
        name:
          - "{{ apache_package }}"
          - "{{ php_package }}"
        state: latest  
        update_cache: yes
        
 
