---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: workstation
  become: true
  roles:
    - worstation

- hosts: web_servers
  become: true
  roles:
    - web_servers

- hosts: db_servers
  become: true
  roles: 
    - db_servers
    
