---

- hosts: all
  become: true
  pre_tasks:


  - name: install updates
    tags: always
    package:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  
  - name: install apache, php and uddate_cache
    tags: always 
    package:
      name: 
        - apache2
        - libapache2-mod-php        
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"
  - name: add php support for apache
    apt:
      name: libapache2-mod-php
      state: latest

- hosts: workstation
  become: true
  tasks:
    
    - name: install terraform
      package:
        name:
          - terraform



- hosts: web_servers
  become: true
  tasks:
   
   - name: copy default html file for site
     tags: apache,apache2
     copy:
       src: default_site.html
       dest: /var/www/html/index.html
       owner: root
       group: root
       mode: 0644
   
   - name: install apache, php and uddate_cache
     tags: apache,apache2,ubuntu
     package:
       name:
         - apache2
         - libapache2-mod-php
       state: latest
       update_cache: yes
     when: ansible_distribution == "Ubuntu" 


- hosts: db_servers
  become: true
  tasks:
   
    - name: install mariadb package
      tags: db,mariadb 
      package:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"
